title: Shuchang (Elvis) Liang # your name (or website title) here
logo: "/images/Profile Photo.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am a Data Analyst at KGS Research Inc. As a continuous follower of the science & analytics field, my enthusiasm in subjects that develop business data analysis and BI visualization boosts my capabilities in the field.
  <br><br>
  Proficient knowledge in statistics, mathematics, and analytics. Strong understanding in poll data analysis, CRM analysis, marketing analysis, A/B testing and machine learning frameworks.
  <br><br>
  <a href="https://www.linkedin.com/in/shuchangl/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
