title:   Arunabho Kanti Som
logo: "/images/Profile.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br><br>
  Results-driven data analyst, product owner and business system analyst with experiences and a track record of delivering innovative technical solutions that enhance the experience of both customers and analytic professionals. 
  <a href="https://www.linkedin.com/in/arunabho-kanti-som/">View My LinkedIn Profile</a>
  <br><br><br>
  <a href="https://public.tableau.com/app/discover">View My Tableau Work Samples</a>
  <br><br><br>
  <a href="https://www.notion.so/">View My Notion Portfolios</a>
  
theme: jekyll-theme-minimal   
 
